=== siliconjungle/ink-knowledge/schemas/entry.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/siliconjungle/ink-knowledge/schemas/entry.json",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema",
    "kind",
    "semantics",
    "dependencies",
    "interface",
    "payload"
  ],
  "properties": {
    "schema": {
      "const": 1
    },
    "kind": {
      "enum": [
        "definition",
        "theorem",
        "rewrite",
        "implementation",
        "representation",
        "maintenance",
        "bridge"
      ]
    },
    "semantics": {
      "type": "string",
      "minLength": 1
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "uniqueItems": true,
      "maxItems": 128
    },
    "interface": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "parameters",
        "result",
        "operations",
        "effects",
        "conditions"
      ],
      "properties": {
        "parameters": {
          "type": "object"
        },
        "result": {},
        "operations": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "effects": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "conditions": {
          "type": "array"
        }
      }
    },
    "payload": {
      "type": "object"
    }
  }
}

=== siliconjungle/ink-knowledge/store/objects/87f3fd732451b0006d8a022ca25ecdff41cc1a41d271b101323bffc4907f55a7.json
{"dependencies":[],"interface":{"conditions":[],"effects":[],"operations":["apply","binary:&&","call:choose","call:foldr"],"parameters":{"p":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]},"q":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]},"xs":{"Value":{"List":{"Named":"A"}}}},"result":{"Value":"Bool"}},"kind":"rewrite","payload":{"assumptions":[{"conditions":[{"from":{"node":{"Op":["apply",[{"node":{"Free":"p"},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]}},{"node":{"Free":"item"},"sort":{"Value":{"Named":"A"}}}]]},"sort":{"Value":"Bool"}},"to":{"node":{"Bool":true},"sort":{"Value":"Bool"}}}],"from":{"node":{"Op":["apply",[{"node":{"Free":"q"},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]}},{"node":{"Free":"item"},"sort":{"Value":{"Named":"A"}}}]]},"sort":{"Value":"Bool"}},"name":"implies","params":{"item":{"Value":{"Named":"A"}}},"to":{"node":{"Bool":true},"sort":{"Value":"Bool"}}}],"conditions":[],"from":{"node":{"Op":["call:choose",[{"node":{"Op":["call:foldr",[{"node":{"Free":"xs"},"sort":{"Value":{"List":{"Named":"A"}}}},{"node":{"Bool":true},"sort":{"Value":"Bool"}},{"node":{"Lambda":{"node":{"Lambda":{"node":{"Op":["binary:&&",[{"node":{"Op":["apply",[{"node":{"Free":"p"},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]}},{"node":{"Bound":1},"sort":{"Value":{"Named":"A"}}}]]},"sort":{"Value":"Bool"}},{"node":{"Bound":0},"sort":{"Value":"Bool"}}]]},"sort":{"Value":"Bool"}}},"sort":{"Arrow":[{"Value":"Bool"},{"Value":"Bool"}]}}},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Arrow":[{"Value":"Bool"},{"Value":"Bool"}]}]}}]]},"sort":{"Value":"Bool"}},{"node":{"Op":["call:foldr",[{"node":{"Free":"xs"},"sort":{"Value":{"List":{"Named":"A"}}}},{"node":{"Bool":true},"sort":{"Value":"Bool"}},{"node":{"Lambda":{"node":{"Lambda":{"node":{"Op":["binary:&&",[{"node":{"Op":["apply",[{"node":{"Free":"q"},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]}},{"node":{"Bound":1},"sort":{"Value":{"Named":"A"}}}]]},"sort":{"Value":"Bool"}},{"node":{"Bound":0},"sort":{"Value":"Bool"}}]]},"sort":{"Value":"Bool"}}},"sort":{"Arrow":[{"Value":"Bool"},{"Value":"Bool"}]}}},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Arrow":[{"Value":"Bool"},{"Value":"Bool"}]}]}}]]},"sort":{"Value":"Bool"}},{"node":{"Bool":true},"sort":{"Value":"Bool"}}]]},"sort":{"Value":"Bool"}},"params":{"p":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]},"q":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]},"xs":{"Value":{"List":{"Named":"A"}}}},"proof":{"Induction":{"base":"Normalize","names":["head","tail"],"step":{"Cases":{"condition":{"node":{"Op":["apply",[{"node":{"Free":"p"},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]}},{"node":{"Free":"head"},"sort":{"Value":{"Named":"A"}}}]]},"sort":{"Value":"Bool"}},"on_false":"Normalize","on_true":{"Cases":{"condition":{"node":{"Op":["apply",[{"node":{"Free":"q"},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]}},{"node":{"Free":"head"},"sort":{"Value":{"Named":"A"}}}]]},"sort":{"Value":"Bool"}},"on_false":{"Cases":{"condition":{"node":{"Op":["call:foldr",[{"node":{"Free":"tail"},"sort":{"Value":{"List":{"Named":"A"}}}},{"node":{"Bool":true},"sort":{"Value":"Bool"}},{"node":{"Lambda":{"node":{"Lambda":{"node":{"Op":["binary:&&",[{"node":{"Op":["apply",[{"node":{"Free":"p"},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]}},{"node":{"Bound":1},"sort":{"Value":{"Named":"A"}}}]]},"sort":{"Value":"Bool"}},{"node":{"Bound":0},"sort":{"Value":"Bool"}}]]},"sort":{"Value":"Bool"}}},"sort":{"Arrow":[{"Value":"Bool"},{"Value":"Bool"}]}}},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Arrow":[{"Value":"Bool"},{"Value":"Bool"}]}]}}]]},"sort":{"Value":"Bool"}},"on_false":"Normalize","on_true":{"Trans":{"left":"Normalize","middle":{"node":{"Op":["apply",[{"node":{"Free":"q"},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]}},{"node":{"Free":"head"},"sort":{"Value":{"Named":"A"}}}]]},"sort":{"Value":"Bool"}},"right":{"Assume":{"arguments":{"item":{"node":{"Free":"head"},"sort":{"Value":{"Named":"A"}}}},"index":0,"premises":["Normalize"]}}}}}},"on_true":{"Trans":{"left":"Normalize","middle":{"node":{"Op":["call:choose",[{"node":{"Op":["call:foldr",[{"node":{"Free":"tail"},"sort":{"Value":{"List":{"Named":"A"}}}},{"node":{"Bool":true},"sort":{"Value":"Bool"}},{"node":{"Lambda":{"node":{"Lambda":{"node":{"Op":["binary:&&",[{"node":{"Op":["apply",[{"node":{"Free":"p"},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]}},{"node":{"Bound":1},"sort":{"Value":{"Named":"A"}}}]]},"sort":{"Value":"Bool"}},{"node":{"Bound":0},"sort":{"Value":"Bool"}}]]},"sort":{"Value":"Bool"}}},"sort":{"Arrow":[{"Value":"Bool"},{"Value":"Bool"}]}}},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Arrow":[{"Value":"Bool"},{"Value":"Bool"}]}]}}]]},"sort":{"Value":"Bool"}},{"node":{"Op":["call:foldr",[{"node":{"Free":"tail"},"sort":{"Value":{"List":{"Named":"A"}}}},{"node":{"Bool":true},"sort":{"Value":"Bool"}},{"node":{"Lambda":{"node":{"Lambda":{"node":{"Op":["binary:&&",[{"node":{"Op":["apply",[{"node":{"Free":"q"},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Value":"Bool"}]}},{"node":{"Bound":1},"sort":{"Value":{"Named":"A"}}}]]},"sort":{"Value":"Bool"}},{"node":{"Bound":0},"sort":{"Value":"Bool"}}]]},"sort":{"Value":"Bool"}}},"sort":{"Arrow":[{"Value":"Bool"},{"Value":"Bool"}]}}},"sort":{"Arrow":[{"Value":{"Named":"A"}},{"Arrow":[{"Value":"Bool"},{"Value":"Bool"}]}]}}]]},"sort":{"Value":"Bool"}},{"node":{"Bool":true},"sort":{"Value":"Bool"}}]]},"sort":{"Value":"Bool"}},"right":{"Hypothesis":0}}}}}}},"variable":"xs"}},"to":{"node":{"Bool":true},"sort":{"Value":"Bool"}},"types":["A"]},"schema":1,"semantics":"ink-general-laws-v1"}

=== siliconjungle/ink-knowledge/store/objects/95f390fe7d3da34138df7df42aee7ca04fe9a914811a26c25c62d6775397d3bb.json
{"dependencies":["0b82c59bf15e551e176949b916544f67dde263a9f75f1ec465ac2b2dbfa26f9d","474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f","6d16b0db4ae1b97f34961bb2f1bd9849a0c413831bbf3b8603988d0c474fbc70","782628ab95dd828a24fb4b442e55f58436200200a31424ec2d88eeac2d8957ac","90d019f3bff7dfad54375d536ab586d6bd583cc7f5740c065404b0d38e8272c5","9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba","a02900963d57d97aa1fe55df523348d493b722a2443aac9e13c6f54caadaf9fc","ad862b00d24208120f5c5b42ce8dd8fb9198b9d2a48530717c923a55dde3e187","dd9122cd0ef5414b8f184fc5a412c2e0c7b9002cb5d701ef49dc7b9f5465679c"],"interface":{"conditions":[{"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"side_left"},{"Var":"right"}],"function":"dd9122cd0ef5414b8f184fc5a412c2e0c7b9002cb5d701ef49dc7b9f5465679c"}}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"side_left"}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}},{"Call":{"arguments":[{"Var":"right"}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}}],"function":"a02900963d57d97aa1fe55df523348d493b722a2443aac9e13c6f54caadaf9fc"}}},{"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"side_right"},{"Var":"right"}],"function":"dd9122cd0ef5414b8f184fc5a412c2e0c7b9002cb5d701ef49dc7b9f5465679c"}}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"side_right"}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}},{"Call":{"arguments":[{"Var":"right"}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}}],"function":"a02900963d57d97aa1fe55df523348d493b722a2443aac9e13c6f54caadaf9fc"}}}],"effects":[],"operations":["call:0b82c59bf15e551e176949b916544f67dde263a9f75f1ec465ac2b2dbfa26f9d","call:474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f","call:a02900963d57d97aa1fe55df523348d493b722a2443aac9e13c6f54caadaf9fc","call:dd9122cd0ef5414b8f184fc5a412c2e0c7b9002cb5d701ef49dc7b9f5465679c"],"parameters":{"right":{"Data":"9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba"},"side_count":"U64","side_height":"U64","side_hi":"U64","side_left":{"Data":"9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba"},"side_lo":"U64","side_right":{"Data":"9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba"},"side_sum":"U64"},"result":null},"kind":"theorem","payload":{"declaration":{"Theorem":{"conditions":[{"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"side_left"},{"Var":"right"}],"function":"dd9122cd0ef5414b8f184fc5a412c2e0c7b9002cb5d701ef49dc7b9f5465679c"}}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"side_left"}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}},{"Call":{"arguments":[{"Var":"right"}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}}],"function":"a02900963d57d97aa1fe55df523348d493b722a2443aac9e13c6f54caadaf9fc"}}},{"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"side_right"},{"Var":"right"}],"function":"dd9122cd0ef5414b8f184fc5a412c2e0c7b9002cb5d701ef49dc7b9f5465679c"}}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"side_right"}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}},{"Call":{"arguments":[{"Var":"right"}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}}],"function":"a02900963d57d97aa1fe55df523348d493b722a2443aac9e13c6f54caadaf9fc"}}}],"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba"}},{"Var":"right"}],"function":"0b82c59bf15e551e176949b916544f67dde263a9f75f1ec465ac2b2dbfa26f9d"}}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}},"params":[["right",{"Data":"9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba"}],["side_left",{"Data":"9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba"}],["side_right",{"Data":"9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba"}],["side_lo","U64"],["side_hi","U64"],["side_sum","U64"],["side_count","U64"],["side_height","U64"]],"proof":{"Trans":[{"Trans":[{"Use":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba"}},{"Var":"right"}],"premises":[],"theorem":"6d16b0db4ae1b97f34961bb2f1bd9849a0c413831bbf3b8603988d0c474fbc70"}},{"Call":{"arguments":[{"Refl":{"Call":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba"}}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}}},{"Refl":{"Call":{"arguments":[{"Var":"right"}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}}}],"function":"a02900963d57d97aa1fe55df523348d493b722a2443aac9e13c6f54caadaf9fc"}}]},{"Use":{"arguments":[{"Var":"right"},{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"premises":[{"Hypothesis":0},{"Hypothesis":1}],"theorem":"ad862b00d24208120f5c5b42ce8dd8fb9198b9d2a48530717c923a55dde3e187"}}]},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"9d8945d011aad39bd2cbae26176ba49ac968ead2dd1578b57377544dd87b74ba"}}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}},{"Call":{"arguments":[{"Var":"right"}],"function":"474aca4c64ac507e51414e3ae5a86dd90b62e855a278e97c55f54a514b35a23f"}}],"function":"a02900963d57d97aa1fe55df523348d493b722a2443aac9e13c6f54caadaf9fc"}}}}},"schema":1,"semantics":"first-order-inductive-equality-v1"}

=== siliconjungle/ink-knowledge/store/objects/4d15276c293799293b39a8431cbcd617cc56e41aeace37f6f58084169da6bb8f.json
{"dependencies":["4afdd054301c0ea19aa84ce4e56f87045589a220aaa7646537eeef1a98549ebd","d001b1994dec9ebd8759d30d8cfb1e0ddbfc9502a693bd1a98bad474b320cbf5","f339924e96a0f1faa8f0889189000a6e336e4b39437ec268a3b71bd085148b25"],"interface":{"conditions":[],"effects":[],"operations":["call:4afdd054301c0ea19aa84ce4e56f87045589a220aaa7646537eeef1a98549ebd"],"parameters":{"rows":{"Data":"d001b1994dec9ebd8759d30d8cfb1e0ddbfc9502a693bd1a98bad474b320cbf5"}},"result":{"Data":"f339924e96a0f1faa8f0889189000a6e336e4b39437ec268a3b71bd085148b25"}},"kind":"definition","payload":{"declaration":{"Function":{"body":{"Match":{"branches":[{"bindings":[],"body":{"Construct":{"arguments":[],"constructor":0,"datatype":"f339924e96a0f1faa8f0889189000a6e336e4b39437ec268a3b71bd085148b25"}}},{"bindings":["key","row","tail"],"body":{"Construct":{"arguments":[{"Call":{"arguments":[{"Var":"row"}],"function":"4afdd054301c0ea19aa84ce4e56f87045589a220aaa7646537eeef1a98549ebd"}},{"SelfCall":[{"Var":"tail"}]}],"constructor":1,"datatype":"f339924e96a0f1faa8f0889189000a6e336e4b39437ec268a3b71bd085148b25"}}}],"scrutinee":{"Var":"rows"}}},"params":[["rows",{"Data":"d001b1994dec9ebd8759d30d8cfb1e0ddbfc9502a693bd1a98bad474b320cbf5"}]],"recursive":0,"result":{"Data":"f339924e96a0f1faa8f0889189000a6e336e4b39437ec268a3b71bd085148b25"}}}},"schema":1,"semantics":"first-order-inductive-equality-v1"}

=== siliconjungle/ink-knowledge/store/objects/fa7bfeb5518049679c7df6aead1b3b6687f505a6bc0e872d8c73a12d563c2ca4.json
{"dependencies":["5fa07af2d0fbc8bf1468deb1820d582b0c8cc24477c6c0c9f4073913f5e2447b","8f271e55ac06a47dbe51e15c43c8b8c0c03e0019b7ea3373717515f395cfcc90","adcd3fa9b78c3423a2204ad28dca815dad36dad9f2d4c473523118840077a669"],"interface":{"conditions":[],"effects":[],"operations":["call:5fa07af2d0fbc8bf1468deb1820d582b0c8cc24477c6c0c9f4073913f5e2447b"],"parameters":{"logical":{"Data":"adcd3fa9b78c3423a2204ad28dca815dad36dad9f2d4c473523118840077a669"},"physical":{"Data":"8f271e55ac06a47dbe51e15c43c8b8c0c03e0019b7ea3373717515f395cfcc90"}},"result":{"Data":"8f271e55ac06a47dbe51e15c43c8b8c0c03e0019b7ea3373717515f395cfcc90"}},"kind":"definition","payload":{"declaration":{"Function":{"body":{"Call":{"arguments":[{"Var":"logical"}],"function":"5fa07af2d0fbc8bf1468deb1820d582b0c8cc24477c6c0c9f4073913f5e2447b"}},"params":[["physical",{"Data":"8f271e55ac06a47dbe51e15c43c8b8c0c03e0019b7ea3373717515f395cfcc90"}],["logical",{"Data":"adcd3fa9b78c3423a2204ad28dca815dad36dad9f2d4c473523118840077a669"}]],"recursive":null,"result":{"Data":"8f271e55ac06a47dbe51e15c43c8b8c0c03e0019b7ea3373717515f395cfcc90"}}}},"schema":1,"semantics":"first-order-inductive-equality-v1"}

=== siliconjungle/ink-knowledge/store/objects/6cbb861e1e3a48c620d3ef0f3db327765e7a531724463373a933620b9e94e1df.json
{"dependencies":["0c85067b81f28551691c880c2dc5267992f53f4779c1c6b767b8b091f6cb2d92","1b2ffc4e25c0c1fced770a98ac53cb2c14883fe1c17c7382d8ba07ae783d20c5","1e9eaedfcc9ddd990078215c323cd6062d64ad0c402aa8f1934e20a0660344c0","1e9f375da8ef648a43f1266636ce3341878694e5ba16d30ad579e152c0913819","2d11fa3d187b1e0a4324b097c0b3dd7c0cf9005531577cb408d302c20b33bec2","3434f686e1987a2a9303539ecca913a993f4d6251f012ee410cb3f2e24af67e7","34b59650fe6d2ba26f9ce07fe577afab7a77aba00b0375c857f54e5f1d56bd3b","5b7383b7d8ffe1e0e399b076aa7dd16f31c80a624adf10542e3c79cf1932787f","5b79e0c0bf10364ad94e0e2c9eb8e0b76a3e1fe59812dce2fdc39ca2563dbef3","61c8c3e1bb9f95a9af20619dbd62fad0c096ffc663643a78cba3d7a2277b8a28","6ee85f9ff598489f71cec322f484df18de1db42ea938f9255ce18813fe998e0e","7cc9b1f30bd0585ff26fde9d7092b26a24d22a6f15c0ce8b971878a9311cc642","9f34d99220027cce18cca80d0de697902964c31cf51b93bf2e58ff6aa3d6eaa5","baa9fb170ac2322a5cbf5fab9c84873a889f82bfd5054af51e8177bfc756899c","c027fba0903ad9a7ca4616e3403216f59cf216012b8f53bd5b48b6a97132d023","c3176609fac43c8d2bea98aa3fb46d3ce2cdcfa3e91782e5dd1fe1d504736d7a","ee312fd83b866d225f57a7c267a11359759f3af15e848ae9cfe360c17e27e8cb","f42cc8625457738db34aacc455c976c9cb46baf6e5af40a76ba65f2cfbec7348"],"interface":{"conditions":[],"effects":[],"operations":["call:3434f686e1987a2a9303539ecca913a993f4d6251f012ee410cb3f2e24af67e7","call:34b59650fe6d2ba26f9ce07fe577afab7a77aba00b0375c857f54e5f1d56bd3b","call:5b7383b7d8ffe1e0e399b076aa7dd16f31c80a624adf10542e3c79cf1932787f"],"parameters":{"arg_0":"U64","arg_1":"U64","arg_2":"U64","physical":{"Data":"c3176609fac43c8d2bea98aa3fb46d3ce2cdcfa3e91782e5dd1fe1d504736d7a"},"version":"U64"},"result":null},"kind":"theorem","payload":{"declaration":{"Theorem":{"conditions":[],"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"physical"}],"function":"5b7383b7d8ffe1e0e399b076aa7dd16f31c80a624adf10542e3c79cf1932787f"}},{"Var":"version"},{"Var":"arg_0"},{"Var":"arg_1"},{"Var":"arg_2"}],"function":"3434f686e1987a2a9303539ecca913a993f4d6251f012ee410cb3f2e24af67e7"}}],"function":"34b59650fe6d2ba26f9ce07fe577afab7a77aba00b0375c857f54e5f1d56bd3b"}}],"function":"5b7383b7d8ffe1e0e399b076aa7dd16f31c80a624adf10542e3c79cf1932787f"}},"params":[["physical",{"Data":"c3176609fac43c8d2bea98aa3fb46d3ce2cdcfa3e91782e5dd1fe1d504736d7a"}],["version","U64"],["arg_0","U64"],["arg_1","U64"],["arg_2","U64"]],"proof":{"Induction":{"cases":[{"bindings":["indexed_root_0","indexed_root_1","indexed_root_2","indexed_root_3","indexed_root_4","indexed_root_5"],"proof":{"Use":{"arguments":[{"Var":"indexed_root_0"},{"Var":"indexed_root_1"},{"Var":"indexed_root_2"},{"Var":"indexed_root_3"},{"Var":"indexed_root_4"},{"Var":"indexed_root_5"},{"Var":"version"},{"Var":"arg_0"},{"Var":"arg_1"},{"Var":"arg_2"}],"premises":[],"theorem":"9f34d99220027cce18cca80d0de697902964c31cf51b93bf2e58ff6aa3d6eaa5"}}}],"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"physical"}],"function":"5b7383b7d8ffe1e0e399b076aa7dd16f31c80a624adf10542e3c79cf1932787f"}},{"Var":"version"},{"Var":"arg_0"},{"Var":"arg_1"},{"Var":"arg_2"}],"function":"3434f686e1987a2a9303539ecca913a993f4d6251f012ee410cb3f2e24af67e7"}}],"function":"34b59650fe6d2ba26f9ce07fe577afab7a77aba00b0375c857f54e5f1d56bd3b"}}],"function":"5b7383b7d8ffe1e0e399b076aa7dd16f31c80a624adf10542e3c79cf1932787f"}},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"physical"}],"function":"5b7383b7d8ffe1e0e399b076aa7dd16f31c80a624adf10542e3c79cf1932787f"}},{"Var":"version"},{"Var":"arg_0"},{"Var":"arg_1"},{"Var":"arg_2"}],"function":"3434f686e1987a2a9303539ecca913a993f4d6251f012ee410cb3f2e24af67e7"}}],"function":"34b59650fe6d2ba26f9ce07fe577afab7a77aba00b0375c857f54e5f1d56bd3b"}},"variable":"physical"}},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"physical"}],"function":"5b7383b7d8ffe1e0e399b076aa7dd16f31c80a624adf10542e3c79cf1932787f"}},{"Var":"version"},{"Var":"arg_0"},{"Var":"arg_1"},{"Var":"arg_2"}],"function":"3434f686e1987a2a9303539ecca913a993f4d6251f012ee410cb3f2e24af67e7"}}],"function":"34b59650fe6d2ba26f9ce07fe577afab7a77aba00b0375c857f54e5f1d56bd3b"}}}}},"schema":1,"semantics":"first-order-inductive-equality-v1"}
