=== siliconjungle/ink-knowledge/schemas/entry.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/siliconjungle/ink-knowledge/schemas/entry.json",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema",
    "kind",
    "semantics",
    "dependencies",
    "interface",
    "payload"
  ],
  "properties": {
    "schema": {
      "const": 1
    },
    "kind": {
      "enum": [
        "definition",
        "theorem",
        "rewrite",
        "implementation",
        "representation",
        "maintenance",
        "bridge"
      ]
    },
    "semantics": {
      "type": "string",
      "minLength": 1
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "uniqueItems": true,
      "maxItems": 128
    },
    "interface": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "parameters",
        "result",
        "operations",
        "effects",
        "conditions"
      ],
      "properties": {
        "parameters": {
          "type": "object"
        },
        "result": {},
        "operations": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "effects": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "conditions": {
          "type": "array"
        }
      }
    },
    "payload": {
      "type": "object"
    }
  }
}

=== siliconjungle/ink-knowledge/store/objects/052daced6670d4e1628673e1bdf5edd32ec42224f17ab0c520c4098e962d8667.json
{"dependencies":["0b2896fb7d4c314eaa4cc523062f4bd60f41252eb902ea01642e234e34631989","110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff","1766594606572caae093691ee36f214bcd9165f3a6e4f8f07f0e2882d2657d20","21fe09113fe56a272ab565ab4aef7285fe5fd5a3732acf7e64eb606601da7041","278f96199151750d38923eeddb65a2c9b439d8b9d36ae2f7f74c9045f0fffb08","348df119634cadd64012c32f53b0ae5bff1045e4f0602ab07e12771c8bca84b9","3b01e83ed63a97250c8f98bfe06df656c66cf51970b389324840292525a5eb7b","6f8e415e736e12c21104a8af10e51765553fc40e02938896d3db102301246906","6fb70d0ae302353570efe099ec6b68ed9f8dbaff3bab8b66be8ff802d60e925a","70e688e22d70f509933d86798827545906a33c9094356ad2715da19f9a858186","782628ab95dd828a24fb4b442e55f58436200200a31424ec2d88eeac2d8957ac","7ab58469556b7477018be1ec17a0774bb1f2faf62ae60a6ba08190b8047763df","7ab6324e9b115ea824495a8cb770f2d2d0381a9ed8f0b9b40f2112c8fd50fd0c","90d019f3bff7dfad54375d536ab586d6bd583cc7f5740c065404b0d38e8272c5","92368800572ebbcfe203c07e2d7e7e00d60743f84b2b815a526d470566792f7f","9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418","adcd3fa9b78c3423a2204ad28dca815dad36dad9f2d4c473523118840077a669","afa16a5a00c36ddb20047c8d864e70e4cf8562c6cba006aad975c40d9b1d4c20","b0bf897e4894cbe32c22fd6076f9458542fbdc25a9641bd507d85784efe0d5ac","baa9fb170ac2322a5cbf5fab9c84873a889f82bfd5054af51e8177bfc756899c","c6927b0865f87bb196f15f68b8badb81fa1be85d4df74ec9dc19dc46fb41576b","d04de2692bfff791846c60726fe4f6855cedbdbf95284fe26bd5d5523a05b14b","e6bf73f7b6192bd23553a508712ea025a084d5377320268e456bca5883de6748","ecb5f0fe765c23cab036dab5aeb85724371c831e3e4d63eb81588998f75d7798"],"interface":{"conditions":[{"from":{"Binary":{"left":{"Call":{"arguments":[{"Var":"left"}],"function":"afa16a5a00c36ddb20047c8d864e70e4cf8562c6cba006aad975c40d9b1d4c20"}},"op":"&&","right":{"Call":{"arguments":[{"Var":"right"}],"function":"afa16a5a00c36ddb20047c8d864e70e4cf8562c6cba006aad975c40d9b1d4c20"}}}},"to":{"Bool":true}},{"from":{"Binary":{"left":{"Call":{"arguments":[{"Var":"left"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}},"op":">","right":{"Binary":{"left":{"Call":{"arguments":[{"Var":"right"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}},"op":"+","right":{"U64":1}}}}},"to":{"Bool":false}},{"from":{"Binary":{"left":{"Call":{"arguments":[{"Var":"right"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}},"op":">","right":{"Binary":{"left":{"Call":{"arguments":[{"Var":"left"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}},"op":"+","right":{"U64":1}}}}},"to":{"Bool":true}},{"from":{"Var":"right"},"to":{"Construct":{"arguments":[{"Var":"tree_case_74_0"},{"Var":"tree_case_74_1"},{"Var":"tree_case_74_2"},{"Var":"tree_case_74_3"},{"Var":"tree_case_74_4"},{"Var":"tree_case_74_5"}],"constructor":2,"datatype":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"}}},{"from":{"Binary":{"left":{"Call":{"arguments":[{"Var":"tree_case_74_1"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}},"op":">=","right":{"Call":{"arguments":[{"Var":"tree_case_74_0"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}}}},"to":{"Bool":false}},{"from":{"Var":"tree_case_74_0"},"to":{"Construct":{"arguments":[{"Var":"tree_case_77_0"},{"Var":"tree_case_77_1"},{"Var":"tree_case_77_2"},{"Var":"tree_case_77_3"},{"Var":"tree_case_77_4"},{"Var":"tree_case_77_5"}],"constructor":2,"datatype":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"}}}],"effects":[],"operations":["binary:&&","binary:+","binary:>","binary:>=","call:110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff","call:7ab6324e9b115ea824495a8cb770f2d2d0381a9ed8f0b9b40f2112c8fd50fd0c","call:afa16a5a00c36ddb20047c8d864e70e4cf8562c6cba006aad975c40d9b1d4c20","call:d04de2692bfff791846c60726fe4f6855cedbdbf95284fe26bd5d5523a05b14b"],"parameters":{"left":{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"},"right":{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"},"tree_case_74_0":{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"},"tree_case_74_1":{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"},"tree_case_74_2":"U64","tree_case_74_3":"U64","tree_case_74_4":"U64","tree_case_74_5":"U64","tree_case_77_0":{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"},"tree_case_77_1":{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"},"tree_case_77_2":"U64","tree_case_77_3":"U64","tree_case_77_4":"U64","tree_case_77_5":"U64"},"result":null},"kind":"theorem","payload":{"declaration":{"Theorem":{"conditions":[{"from":{"Binary":{"left":{"Call":{"arguments":[{"Var":"left"}],"function":"afa16a5a00c36ddb20047c8d864e70e4cf8562c6cba006aad975c40d9b1d4c20"}},"op":"&&","right":{"Call":{"arguments":[{"Var":"right"}],"function":"afa16a5a00c36ddb20047c8d864e70e4cf8562c6cba006aad975c40d9b1d4c20"}}}},"to":{"Bool":true}},{"from":{"Binary":{"left":{"Call":{"arguments":[{"Var":"left"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}},"op":">","right":{"Binary":{"left":{"Call":{"arguments":[{"Var":"right"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}},"op":"+","right":{"U64":1}}}}},"to":{"Bool":false}},{"from":{"Binary":{"left":{"Call":{"arguments":[{"Var":"right"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}},"op":">","right":{"Binary":{"left":{"Call":{"arguments":[{"Var":"left"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}},"op":"+","right":{"U64":1}}}}},"to":{"Bool":true}},{"from":{"Var":"right"},"to":{"Construct":{"arguments":[{"Var":"tree_case_74_0"},{"Var":"tree_case_74_1"},{"Var":"tree_case_74_2"},{"Var":"tree_case_74_3"},{"Var":"tree_case_74_4"},{"Var":"tree_case_74_5"}],"constructor":2,"datatype":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"}}},{"from":{"Binary":{"left":{"Call":{"arguments":[{"Var":"tree_case_74_1"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}},"op":">=","right":{"Call":{"arguments":[{"Var":"tree_case_74_0"}],"function":"110ad60f3c1683f6b79607a26ebc37c047562e55dd505d396196a1cf0e47d0ff"}}}},"to":{"Bool":false}},{"from":{"Var":"tree_case_74_0"},"to":{"Construct":{"arguments":[{"Var":"tree_case_77_0"},{"Var":"tree_case_77_1"},{"Var":"tree_case_77_2"},{"Var":"tree_case_77_3"},{"Var":"tree_case_77_4"},{"Var":"tree_case_77_5"}],"constructor":2,"datatype":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"}}}],"from":{"If":{"condition":{"Binary":{"left":{"Call":{"arguments":[{"Var":"left"}],"function":"afa16a5a00c36ddb20047c8d864e70e4cf8562c6cba006aad975c40d9b1d4c20"}},"op":"&&","right":{"Call":{"arguments":[{"Var":"right"}],"function":"afa16a5a00c36ddb20047c8d864e70e4cf8562c6cba006aad975c40d9b1d4c20"}}}},"on_false":{"Bool":true},"on_true":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"},{"Var":"right"}],"function":"7ab6324e9b115ea824495a8cb770f2d2d0381a9ed8f0b9b40f2112c8fd50fd0c"}}],"function":"afa16a5a00c36ddb20047c8d864e70e4cf8562c6cba006aad975c40d9b1d4c20"}}}},"params":[["left",{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"}],["right",{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"}],["tree_case_74_0",{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"}],["tree_case_74_1",{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"}],["tree_case_74_2","U64"],["tree_case_74_3","U64"],["tree_case_74_4","U64"],["tree_case_74_5","U64"],["tree_case_77_0",{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"}],["tree_case_77_1",{"Data":"9d88fbbc16997ba4b9de305ab59459ccdb526b74c4ee3b4cfeef7e18b1d18418"}],["tree_case_77_2","U64"],["tree_case_77_3","U64"],["tree_case_77_4","U64"],["tree_case_77_5","U64"]],"proof":{"Trans":[{"Use":{"arguments":[{"Var":"left"},{"Var":"right"},{"Var":"tree_case_74_0"},{"Var":"tree_case_74_1"},{"Var":"tree_case_74_2"},{"Var":"tree_case_74_3"},{"Var":"tree_case_74_4"},{"Var":"tree_case_74_5"},{"Var":"tree_case_77_0"},{"Var":"tree_case_77_1"},{"Var":"tree_case_77_2"},{"Var":"tree_case_77_3"},{"Var":"tree_case_77_4"},{"Var":"tree_case_77_5"}],"premises":[{"Hypothesis":0},{"Hypothesis":1},{"Hypothesis":2},{"Hypothesis":3},{"Hypothesis":4},{"Hypothesis":5}],"theorem":"348df119634cadd64012c32f53b0ae5bff1045e4f0602ab07e12771c8bca84b9"}},{"Substitute":{"context":{"Var":"tree_proof_hole"},"equality":{"Use":{"arguments":[{"Call":{"arguments":[{"Var":"left"},{"Var":"tree_case_77_0"}],"function":"d04de2692bfff791846c60726fe4f6855cedbdbf95284fe26bd5d5523a05b14b"}},{"Call":{"arguments":[{"Var":"tree_case_77_1"},{"Var":"tree_case_74_1"}],"function":"d04de2692bfff791846c60726fe4f6855cedbdbf95284fe26bd5d5523a05b14b"}}],"premises":[{"Use":{"arguments":[{"Var":"left"},{"Var":"right"},{"Var":"tree_case_74_0"},{"Var":"tree_case_74_1"},{"Var":"tree_case_74_2"},{"Var":"tree_case_74_3"},{"Var":"tree_case_74_4"},{"Var":"tree_case_74_5"},{"Var":"tree_case_77_0"},{"Var":"tree_case_77_1"},{"Var":"tree_case_77_2"},{"Var":"tree_case_77_3"},{"Var":"tree_case_77_4"},{"Var":"tree_case_77_5"}],"premises":[{"Hypothesis":0},{"Hypothesis":1},{"Hypothesis":2},{"Hypothesis":3},{"Hypothesis":4},{"Hypothesis":5}],"theorem":"e6bf73f7b6192bd23553a508712ea025a084d5377320268e456bca5883de6748"}}],"theorem":"ecb5f0fe765c23cab036dab5aeb85724371c831e3e4d63eb81588998f75d7798"}},"variable":"tree_proof_hole"}}]},"to":{"Bool":true}}}},"schema":1,"semantics":"first-order-inductive-equality-v1"}

=== siliconjungle/ink-knowledge/store/objects/9eb8e43f9f3e68be92ba335f9bb3e035b2746a6860c960b05dff7b4965c532fc.json
{"dependencies":["18e84eab07c91c68fcfef365105156492ed923514972942965d506d59bf27e5a","4c3359113b8476afb07c623c49d2bb57487e0f388609f2111ab0103adcbd7fe6","5e43b5c105efacfdf935b54f8701cebf3674d19451fc2ab6f85d8884f1f6117c","985b1d3a3ef84acfec5b04cc0e97f02e37a90a94531f2d44e70441b065ddbfc7","aa4b4d10ded23af26918448553b80f26334c687b7cd335992439f98655348d79","ade150fd8ed7b5b69f3cf01969b73ebc324ef8f93b6c477e1d689d88bfa4bdf9","b8b70ac79f10e9d48f64ae5b9b8bed9e087b35a3f7256813c98df4f783dfecd6","bdc38dcc7fa6ea9ed6c270fe78680793965be480ec5e0eea41136eba8dc218fe","c12231e9fa0f02135491772f8d3f3ace10d8b9d1d5c3ea70dc152db403f8249e","ddd2014acc147fd2466912ac6e0d88d01968724066460083896586da77415146","e66ab993ade255a3f7a1d5d0f2afc01ae46054686cdff91ea86a6fae24331f13","ede44dcc7c284e4f7057eea0c0be788c9bc3c0229fb607c58dc92f41d20edf49"],"interface":{"conditions":[],"effects":[],"operations":[],"parameters":{"traverse_rows":{"Data":"bdc38dcc7fa6ea9ed6c270fe78680793965be480ec5e0eea41136eba8dc218fe"}},"result":{"Data":"bdc38dcc7fa6ea9ed6c270fe78680793965be480ec5e0eea41136eba8dc218fe"}},"kind":"definition","payload":{"declaration":{"Function":{"body":{"Match":{"branches":[{"bindings":[],"body":{"Construct":{"arguments":[],"constructor":0,"datatype":"bdc38dcc7fa6ea9ed6c270fe78680793965be480ec5e0eea41136eba8dc218fe"}}},{"bindings":["traverse_head","traverse_tail"],"body":{"If":{"condition":{"Match":{"branches":[{"bindings":["model_61","model_62","model_63"],"body":{"Var":"model_63"}}],"scrutinee":{"Var":"traverse_head"}}},"on_false":{"SelfCall":[{"Var":"traverse_tail"}]},"on_true":{"Construct":{"arguments":[{"Var":"traverse_head"},{"SelfCall":[{"Var":"traverse_tail"}]}],"constructor":1,"datatype":"bdc38dcc7fa6ea9ed6c270fe78680793965be480ec5e0eea41136eba8dc218fe"}}}}}],"scrutinee":{"Var":"traverse_rows"}}},"params":[["traverse_rows",{"Data":"bdc38dcc7fa6ea9ed6c270fe78680793965be480ec5e0eea41136eba8dc218fe"}]],"recursive":0,"result":{"Data":"bdc38dcc7fa6ea9ed6c270fe78680793965be480ec5e0eea41136eba8dc218fe"}}}},"schema":1,"semantics":"first-order-inductive-equality-v1"}

=== siliconjungle/ink-knowledge/store/objects/3f70d1b6cc027cca8604148fbe4c1245920e46cc2485e24c9b67d95dc9da6276.json
{"dependencies":["0c44e7a5924949ef4be3f74a88ac769056679cbd1044d51c55b5811c209db23e","128fc930ccf41033270e2cf4035a565b3f379fd2f832190bc6da2cdc81517708","18e84eab07c91c68fcfef365105156492ed923514972942965d506d59bf27e5a","1c3399f72405adf5f8995d621f0c490f85412137ce32d0ae8c4d35ba646a8440","229f5da6fe5911a65a7a746debc49a69dd5d017523342f5dd17cd81925af6f9e","23f04b27c737dcfbef2ad51aca65d6554fb5fcf0124a7415b384c9fbe0e67613","2b176851f6252cdb33dc8eca46896a90b915bb68631601b230e4eea2ae2b2068","431bf715934b9480c7d9096730aaf1b7d18e74d31d28ab1a994e8e0cc082e379","5e43b5c105efacfdf935b54f8701cebf3674d19451fc2ab6f85d8884f1f6117c","60a5764f00d632c4513f33b23a4e389c5dfc8ff8f93bcc7056be5e83a37ab109","614aa32311cffd84621d040de21feaf9664558ece6e1ca76ca0c210fe950a8a9","66496c1b0e3c5dec09aa13fa726d83fa5aafe93fe06cab9657a50530537e0494","6f5098c4226d33473b51c00c067abf0010658eb16f99306e7ac9fb7ee88e7a31","9c900b60fd87699585726d5e9a110ef7e116f9b9169d54b6db7104c1a74af2fd","ade150fd8ed7b5b69f3cf01969b73ebc324ef8f93b6c477e1d689d88bfa4bdf9","c12231e9fa0f02135491772f8d3f3ace10d8b9d1d5c3ea70dc152db403f8249e","c2e1e03b8a26eef92bdda35af891d1f0d033565e90c17f935d819584ee0491a5","d09bf43453f100816a60694f2c532e721de965c45716ae4564f2c2eaaf0f7c2f","d40747354b5c8feb90acf7f6fcffed59198bc80764a2e27ce0578d17a1e64631","d611d48b1d32a109dc93883a2a8923a76a7d92adbabcb2c682a92d8ef30985d8","ed3228ffda95e20181a83e246b5851d38bafca79dca82a82fec2b45e37d3aa90","f015abc2f341ae2e1298aafd99d4022be248977c55f961b452878c729d2613b0","f05183b3c7a3a7aaf4ca3228a3a055bca781683d3a285a342755a8a570a9fa90"],"interface":{"conditions":[],"effects":[],"operations":["binary:+","binary:-"],"parameters":{"word_0":"U64","word_1":"U64","word_2":"U64","word_3":"U64"},"result":null},"kind":"theorem","payload":{"declaration":{"Theorem":{"conditions":[],"from":{"Binary":{"left":{"Var":"word_1"},"op":"+","right":{"Binary":{"left":{"Var":"word_3"},"op":"+","right":{"Binary":{"left":{"Var":"word_0"},"op":"+","right":{"Binary":{"left":{"Var":"word_2"},"op":"+","right":{"Binary":{"left":{"U64":0},"op":"-","right":{"Var":"word_3"}}}}}}}}}}},"params":[["word_0","U64"],["word_1","U64"],["word_2","U64"],["word_3","U64"]],"proof":{"Trans":[{"Use":{"arguments":[{"Var":"word_0"},{"Var":"word_1"},{"Var":"word_2"},{"Var":"word_3"}],"premises":[],"theorem":"0c44e7a5924949ef4be3f74a88ac769056679cbd1044d51c55b5811c209db23e"}},{"Binary":{"left":{"Refl":{"Var":"word_0"}},"op":"+","right":{"Binary":{"left":{"Refl":{"Var":"word_1"}},"op":"+","right":{"Binary":{"left":{"Refl":{"Var":"word_2"}},"op":"+","right":{"Use":{"arguments":[{"Var":"word_3"}],"premises":[],"theorem":"1c3399f72405adf5f8995d621f0c490f85412137ce32d0ae8c4d35ba646a8440"}}}}}}}}]},"to":{"Binary":{"left":{"Var":"word_0"},"op":"+","right":{"Binary":{"left":{"Var":"word_1"},"op":"+","right":{"Binary":{"left":{"Var":"word_2"},"op":"+","right":{"U64":0}}}}}}}}}},"schema":1,"semantics":"first-order-inductive-equality-v1"}

=== siliconjungle/ink-knowledge/store/objects/303e4fb0f3a7bead072ec0877b75d08576389f83f6d17d0145ff508cee2c5655.json
{"dependencies":["38cae3e98f3eed1778882b4c5d6ccd78a2dcd29b1d57d40d9eb4e6665ed5d52f","3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad","457dc329cc9179fc67d53dd5ad504cba9495f603dff7e2238faece0cbeb16ede","623885d122fb8f1a0e5f6dae96c71d19d96fbbde220312c01fd88daafbad5cee","6bc9cae150bb03674803b216374db6f3c1732ddd4e7dc088fd21056c84e6f658","6c9efc7cee62903e012b7b63ac0f516956950eca03c8cb4f0d05c2bbf5d9b53c","8cec548bbc3a690bd52bdf434f7df2bb7e3c5601125c2677c5d01e1f8a95cf5b","9b2300f15c1f482f118af175638ba983fefa89b0ede6b02bbccb9c51aba593ad","af255cddcfb8e0b31b2792099593ce3916db30d0d49bf251c4c4754f61920b34","bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91","e5f61ad93af004043b8ff94b0a1accdb996df550102461885e7e67f5b405b1ce"],"interface":{"conditions":[{"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"},{"Var":"side_left"}],"function":"38cae3e98f3eed1778882b4c5d6ccd78a2dcd29b1d57d40d9eb4e6665ed5d52f"}}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},{"Call":{"arguments":[{"Var":"side_left"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}}],"function":"e5f61ad93af004043b8ff94b0a1accdb996df550102461885e7e67f5b405b1ce"}}},{"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"},{"Var":"side_right"}],"function":"38cae3e98f3eed1778882b4c5d6ccd78a2dcd29b1d57d40d9eb4e6665ed5d52f"}}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},{"Call":{"arguments":[{"Var":"side_right"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}}],"function":"e5f61ad93af004043b8ff94b0a1accdb996df550102461885e7e67f5b405b1ce"}}}],"effects":[],"operations":["binary:+","binary:>","call:38cae3e98f3eed1778882b4c5d6ccd78a2dcd29b1d57d40d9eb4e6665ed5d52f","call:3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad","call:6bc9cae150bb03674803b216374db6f3c1732ddd4e7dc088fd21056c84e6f658","call:9b2300f15c1f482f118af175638ba983fefa89b0ede6b02bbccb9c51aba593ad","call:e5f61ad93af004043b8ff94b0a1accdb996df550102461885e7e67f5b405b1ce"],"parameters":{"left":{"Data":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"},"side_count":"U64","side_height":"U64","side_hi":{"Data":"623885d122fb8f1a0e5f6dae96c71d19d96fbbde220312c01fd88daafbad5cee"},"side_left":{"Data":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"},"side_lo":{"Data":"623885d122fb8f1a0e5f6dae96c71d19d96fbbde220312c01fd88daafbad5cee"},"side_right":{"Data":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"},"side_sum":{"Data":"457dc329cc9179fc67d53dd5ad504cba9495f603dff7e2238faece0cbeb16ede"}},"result":null},"kind":"theorem","payload":{"declaration":{"Theorem":{"conditions":[{"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"},{"Var":"side_left"}],"function":"38cae3e98f3eed1778882b4c5d6ccd78a2dcd29b1d57d40d9eb4e6665ed5d52f"}}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},{"Call":{"arguments":[{"Var":"side_left"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}}],"function":"e5f61ad93af004043b8ff94b0a1accdb996df550102461885e7e67f5b405b1ce"}}},{"from":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"},{"Var":"side_right"}],"function":"38cae3e98f3eed1778882b4c5d6ccd78a2dcd29b1d57d40d9eb4e6665ed5d52f"}}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},"to":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},{"Call":{"arguments":[{"Var":"side_right"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}}],"function":"e5f61ad93af004043b8ff94b0a1accdb996df550102461885e7e67f5b405b1ce"}}}],"from":{"If":{"condition":{"Binary":{"left":{"Call":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}}],"function":"6bc9cae150bb03674803b216374db6f3c1732ddd4e7dc088fd21056c84e6f658"}},"op":">","right":{"Binary":{"left":{"Call":{"arguments":[{"Var":"left"}],"function":"6bc9cae150bb03674803b216374db6f3c1732ddd4e7dc088fd21056c84e6f658"}},"op":"+","right":{"U64":1}}}}},"on_false":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"},{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}}],"function":"9b2300f15c1f482f118af175638ba983fefa89b0ede6b02bbccb9c51aba593ad"}}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},"on_true":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},{"Call":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}}],"function":"e5f61ad93af004043b8ff94b0a1accdb996df550102461885e7e67f5b405b1ce"}}}},"params":[["left",{"Data":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}],["side_left",{"Data":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}],["side_right",{"Data":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}],["side_lo",{"Data":"623885d122fb8f1a0e5f6dae96c71d19d96fbbde220312c01fd88daafbad5cee"}],["side_hi",{"Data":"623885d122fb8f1a0e5f6dae96c71d19d96fbbde220312c01fd88daafbad5cee"}],["side_sum",{"Data":"457dc329cc9179fc67d53dd5ad504cba9495f603dff7e2238faece0cbeb16ede"}],["side_count","U64"],["side_height","U64"]],"proof":{"Substitute":{"context":{"If":{"condition":{"Binary":{"left":{"Call":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}}],"function":"6bc9cae150bb03674803b216374db6f3c1732ddd4e7dc088fd21056c84e6f658"}},"op":">","right":{"Binary":{"left":{"Call":{"arguments":[{"Var":"left"}],"function":"6bc9cae150bb03674803b216374db6f3c1732ddd4e7dc088fd21056c84e6f658"}},"op":"+","right":{"U64":1}}}}},"on_false":{"Var":"prune_hole"},"on_true":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},{"Call":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}}],"function":"e5f61ad93af004043b8ff94b0a1accdb996df550102461885e7e67f5b405b1ce"}}}},"equality":{"Use":{"arguments":[{"Var":"left"},{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"premises":[{"Hypothesis":0},{"Hypothesis":1}],"theorem":"af255cddcfb8e0b31b2792099593ce3916db30d0d49bf251c4c4754f61920b34"}},"variable":"prune_hole"}},"to":{"If":{"condition":{"Binary":{"left":{"Call":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}}],"function":"6bc9cae150bb03674803b216374db6f3c1732ddd4e7dc088fd21056c84e6f658"}},"op":">","right":{"Binary":{"left":{"Call":{"arguments":[{"Var":"left"}],"function":"6bc9cae150bb03674803b216374db6f3c1732ddd4e7dc088fd21056c84e6f658"}},"op":"+","right":{"U64":1}}}}},"on_false":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},{"Call":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}}],"function":"e5f61ad93af004043b8ff94b0a1accdb996df550102461885e7e67f5b405b1ce"}},"on_true":{"Call":{"arguments":[{"Call":{"arguments":[{"Var":"left"}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}},{"Call":{"arguments":[{"Construct":{"arguments":[{"Var":"side_left"},{"Var":"side_right"},{"Var":"side_lo"},{"Var":"side_hi"},{"Var":"side_sum"},{"Var":"side_count"},{"Var":"side_height"}],"constructor":2,"datatype":"bd4b65fd5a8087237ea35c9bb4711c70fc63338b07fb79b103eff79b0c7cce91"}}],"function":"3bfd71913a96ad9512901f6734ca5cd2fd967edf57130ed015fdb1b384bcd7ad"}}],"function":"e5f61ad93af004043b8ff94b0a1accdb996df550102461885e7e67f5b405b1ce"}}}}}}},"schema":1,"semantics":"first-order-inductive-equality-v1"}
